export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO"
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO"
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR"

export const DESCARGAR_PRODUCTOS = "DESCARGAR_PRODUCTOS"
export const DESCARGAR_PRODUCTOS_EXITO = "DESCARGAR_PRODUCTOS_EXITO"
export const DESCARGAR_PRODUCTOS_ERROR = "DESCARGAR_PRODUCTOS_ERROR"

export const DESCARGAR_PRODUCTO = "DESCARGAR_PRODUCTO"
export const DESCARGAR_PRODUCTO_EXITO = "DESCARGAR_PRODUCTO_EXITO"
export const DESCARGAR_PRODUCTO_ERROR = "DESCARGAR_PRODUCTO_ERROR"

export const OBTENER_PRODUCTO_EDITAR = "OBTENER_PRODUCTO_EDITAR"
export const COMENZAR_EDICION_PRODUCTO = "COMENZAR_EDICION_PRODUCTO"
export const EDITAR_PRODUCTO_EXITO = "EDITAR_PRODUCTO_EXITO"
export const EDITAR_PRODUCTO_ERROR = "EDITAR_PRODUCTO_ERROR"

export const OBTENER_PRODUCTO_ELIMINAR = "OBTENER_PRODUCTO_ELIMINAR"
export const ELIMINAR_PRODUCTO_EXITO = "ELIMINAR_PRODUCTO_EXITO"
export const ELIMINAR_PRODUCTO_ERROR = "ELIMINAR_PRODUCTO_ERROR"

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA"
export const OCULTAR_ALERTA = "OCULTAR_ALERTA"
